#!/usr/bin/env bash

# Load theme
source-file ~/.tmux/themes/tokyonight_night.tmux

# Appearance tweaks
set-option -g status-position top

set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"

set -g base-index 1
set -g pane-base-index 1

# Load keybinds
source-file ~/.tmux/keybinds.tmux

# Enable mouse support
set -g mouse on

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'christoomey/vim-tmux-navigator'

run '~/.tmux/plugins/tpm/tpm'

