---@type LazySpec
return {
  "nvim-neo-tree/neo-tree.nvim",
  opts = {
    close_if_last_window = true,
    filesystem = {
      filtered_items = {
        hide_dotfiles = false,
        hide_gitignored = true,
        hide_ignored = true,
        hide_by_name = {
          ".DS_Store",
          "thumbs.db",
          ".1password",
          ".aws",
          ".bun",
          ".cache",
          ".cargo",
          ".copilot",
          ".docker",
          ".dotnet",
          ".eclipse",
          ".gnupg",
          ".luarocks",
          ".mitmproxy",
          ".mozilla",
          ".npm",
          ".nv",
          ".nvm",
          ".password-store",
          ".pki",
          ".steam",
          ".swt",
          ".terraform.d",
          ".vscode",
          ".vscode-oss",
          ".w3m",
          ".wine",
          ".yarn",
          ".bashrc",
          ".bash_history",
          ".bash_logout",
          ".bash_profile",
          ".nvidia-settings-rc",
          ".pulse-cookie",
          ".shell.pre-oh-my-zsh",
          ".steampid",
          ".wget-hsts",
          ".xinitrc",
          ".zcompdump-archlinux-5.9",
          ".zcompdump-archlinux-5.9.zwc",
          ".zsh_history",
          ".zsh_history.bak",
          ".zshrc.bak",
        },
        always_show = {
          ".gitignore",
          ".env",
        },
        always_show_by_pattern = {
          "**.config",
        },
      },
    },
  },
}
